py_library(
    name = "sample",
    srcs = ["sample.py"],
    deps = [
    ],
)


py_test(
    name = "sample_test",
    size = "small",
    srcs = ["sample_test.py"],
    deps = [
        ":sample",
    ],
)
